### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by LinaIssa** [WilfriedMercier/Sphere#1]
Dear Wilfried Mercier, 

I would be utterly honored if you could have a look at my bugs :) 🥇 

Sincerely yours 

Here is a snap of my terminal 
 Traceback (most recent call last):                                                                                        
  File "/Users/linaissa/anaconda3/bin/ipython", line 11, in <module>
    sys.exit(start_ipython())
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/__init__.py", line 125, in start_ipython
    return launch_new_instance(argv=argv, **kwargs)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/terminal/ipapp.py", line 356, in start
    self.shell.mainloop()
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 498, in mainloop
    self.interact()
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 481, in interact
    code = self.prompt_for_code()
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 410, in prompt_for_code
    **self._extra_prompt_options())
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 738, in prompt
    return run_sync()
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 727, in run_sync
    return self.app.run(inputhook=self.inputhook, pre_run=pre_run2)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 682, in run
    run_until_complete(f, inputhook=inputhook)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/eventloop/defaults.py", line 123, in run_until_complete
    return get_event_loop().run_until_complete(future, inputhook=inputhook)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 66, in run_until_complete
    self._run_once(inputhook)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 85, in _run_once
    self._inputhook_context.call_inputhook(ready, inputhook)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/prompt_toolkit/eventloop/inputhook.py", line 81, in call_inputhook
    inputhook(self)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/terminal/interactiveshell.py", line 513, in inputhook
    self._inputhook(context)
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/terminal/pt_inputhooks/tk.py", line 88, in inputhook
    wait_using_filehandler()
  File "/Users/linaissa/anaconda3/lib/python3.7/site-packages/IPython/terminal/pt_inputhooks/tk.py", line 65, in wait_using_filehandler
    root.createfilehandler(inputhook_context.fileno(), _tkinter.READABLE, done)
RuntimeError: Calling Tcl from different apartment

If you suspect this is an IPython bug, please report it at:
    https://github.com/ipython/ipython/issues
or send an email to the mailing list at ipython-dev@python.org

You can print a more detailed traceback right now with "%tb", or use "%debug"
to interactively debug it.

Extra-detailed tracebacks for bug-reporting purposes can be enabled via:
    %config Application.verbose_crash=True

2020-10-19 14:00:29.017 python[2423:63972] WARNING: NSWindow drag regions should only be invalidated on the Main Thread! This will throw an exception in the future. Called from (
	0   AppKit                              0x00007fff3391e7f0 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 371
	1   AppKit                              0x00007fff3391bce1 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	2   AppKit                              0x00007fff3391b753 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	3   libtk8.6.dylib                      0x000000011a22d426 TkMacOSXMakeRealWindowExist + 742
	4   libtk8.6.dylib                      0x000000011a233c04 ApplyWindowAttributeFlagChanges + 196
	5   libtk8.6.dylib                      0x000000011a2318a5 Tk_WmObjCmd + 14293
	6   libtcl8.6.dylib                     0x0000000119fc7b26 Tcl_EvalObjv + 342
	7   _tkinter.cpython-37m-darwin.so      0x0000000119f9a572 Tkapp_Call + 210
	8   python                              0x000000010deaf18e _PyMethodDef_RawFastCallKeywords + 350
	9   python                              0x000000010debbe64 _PyMethodDescr_FastCallKeywords + 84
	10  python                              0x000000010dfebec5 call_function + 437
	11  python                              0x000000010dfe9a56 _PyEval_EvalFrameDefault + 45942
	12  python                              0x000000010dfdd49e _PyEval_EvalCodeWithName + 414
	13  python                              0x000000010deaefe3 _PyFunction_FastCallKeywords + 195
	14  python                              0x000000010dfebdc7 call_function + 183
	15  python                              0x000000010dfe9be0 _PyEval_EvalFrameDefault + 46336
	16  python                              0x000000010dfdd49e _PyEval_EvalCodeWithName + 414
	17  python                              0x000000010deadde7 _PyFunction_FastCallDict + 231
	18  python                              0x000000010df30381 slot_tp_init + 193
	19  python                              0x000000010df3a361 type_call + 241
	20  python                              0x000000010deaeae3 _PyObject_FastCallKeywords + 179
	21  python                              0x000000010dfebed5 call_function + 453
	22  python                              0x000000010dfe9be0 _PyEval_EvalFrameDefault + 46336
	23  python                              0x000000010dfdd49e _PyEval_EvalCodeWithName + 414
	24  python                              0x000000010deadde7 _PyFunction_FastCallDict + 231
	25  python                              0x000000010df30381 slot_tp_init + 193
	26  python                              0x000000010df3a361 type_call + 241
	27  python                              0x000000010deaeae3 _PyObject_FastCallKeywords + 179
	28  python                              0x000000010dfebed5 call_function + 453
	29  python                              0x000000010dfe9b27 _PyEval_EvalFrameDefault + 46151
	30  python                              0x000000010deae8d5 function_code_fastcall + 117
	31  python                              0x000000010dfebdc7 call_function + 183
	32  python                              0x000000010dfe9a56 _PyEval_EvalFrameDefault + 45942
	33  python                              0x000000010deae8d5 function_code_fastcall + 117
	34  python                              0x000000010dfebdc7 call_function + 183
	35  python                              0x000000010dfe9a56 _PyEval_EvalFrameDefault + 45942
	36  python                              0x000000010deae8d5 function_code_fastcall + 117
	37  python                              0x000000010deb1ce2 method_call + 130
	38  python                              0x000000010deaf752 PyObject_Call + 130
	39  python                              0x000000010e0cd8cb t_bootstrap + 123
	40  python                              0x000000010e054707 pythread_wrapper + 39
	41  libsystem_pthread.dylib             0x00007fff6db93d76 _pthread_start + 125
	42  libsystem_pthread.dylib             0x00007fff6db905d7 thread_start + 15
)
Exception in thread Thread-193:
Traceback (most recent call last):
  File "/Users/linaissa/anaconda3/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/Users/linaissa/Documents/Willou/Sphere-master/__main__.py", line 301, in run
    app  = mainApplication(self.root)
  File "/Users/linaissa/Documents/Willou/Sphere-master/__main__.py", line 105, in __init__
    self.iconDict['FOLDER']     = tk.BitmapImage(data=icons['FOLDER'],     maskdata=icons['FOLDER_MASK'],     background='goldenrod')
KeyError: 'FOLDER'

(base) MacBook-Air-de-Lina:Sphere-master linaissa$

**Comment by WilfriedMercier** [comment]
Hi Lina,
I do not have a MAC on my side to check but on Ubuntu I do not have this issue.
From the error message, it looks like the program does not know the folder.xbm and folder_mask.xbm icons. Could you check that you recovered them in icon folder and if not retrieve them and retry ?
Wilfried
